version: '3.8'
services:
  app:
    build: .
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
